package com.example.testdataservice.service; import com.example.testdataservice.dto.TestDataDto; import com.example.testdataservice.repo.TestDataRepository; import com.example.testdataservice.config.EnvironmentContext; import org.springframework.core.env.Environment; import org.springframework.data.redis.core.*; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.*; import java.util.concurrent.TimeUnit;
@Service public class RedisAllocationService {
    private final RedisTemplate<String,String> redis; private final TestDataRepository jpaRepo; private final int leaseSeconds;
    public RedisAllocationService(RedisTemplate<String,String> redis, TestDataRepository jpaRepo, Environment env){ this.redis=redis; this.jpaRepo=jpaRepo; this.leaseSeconds=Integer.parseInt(env.getProperty("app.lease.seconds","600")); }
    private String prefix(String e){return "env:"+e+":";} private String poolList(String e,String type){return prefix(e)+"pool:list:"+type;} private String inuseList(String e,String type){return prefix(e)+"inuse:list:"+type;} private String poolSet(String e,String type){return prefix(e)+"pool:set:"+type;} private String inuseSet(String e,String type){return prefix(e)+"inuse:set:"+type;} private String typesSet(String e){return prefix(e)+"types:set";} private String dataKey(String e,Long id){return prefix(e)+"data:"+id;} private String leaseKey(String e,Long id){return prefix(e)+"lease:"+id;}
    public void upsertTestDataForEnv(String e, TestDataDto dto){ HashOperations<String,String,String> hash=redis.opsForHash(); String dkey=dataKey(e,dto.getId()); hash.put(dkey,"id",dto.getId().toString()); hash.put(dkey,"type",dto.getType()); hash.put(dkey,"payload",dto.getPayload()); hash.put(dkey,"syncedAt",dto.getSyncedAt().toString()); redis.opsForSet().add(typesSet(e), dto.getType()); if(!redis.opsForSet().isMember(poolSet(e,dto.getType()), dto.getId().toString()) && !redis.opsForSet().isMember(inuseSet(e,dto.getType()), dto.getId().toString())) { redis.opsForList().leftPush(poolList(e,dto.getType()), dto.getId().toString()); redis.opsForSet().add(poolSet(e,dto.getType()), dto.getId().toString()); } }
    public Optional<TestDataDto> allocate(String e, String type){ String id = redis.opsForList().rightPopAndLeftPush(poolList(e,type), inuseList(e,type)); if(id==null) return Optional.empty(); redis.opsForSet().remove(poolSet(e,type), id); redis.opsForSet().add(inuseSet(e,type), id); Long lid=Long.valueOf(id); redis.opsForValue().set(leaseKey(e,lid), String.valueOf(System.currentTimeMillis()), leaseSeconds, TimeUnit.SECONDS); Map<String,String> entries = redis.opsForHash().entries(dataKey(e,lid)); if(entries==null || entries.isEmpty()){ jpaRepo.findById(lid).ifPresent(ent -> upsertTestDataForEnv(e, new TestDataDto(ent.getId(), ent.getType(), ent.getPayload(), Instant.now()))); entries = redis.opsForHash().entries(dataKey(e,lid)); } if(entries==null || entries.isEmpty()) return Optional.empty(); return Optional.of(new TestDataDto(Long.valueOf(entries.get("id")), entries.get("type"), entries.get("payload"), Instant.parse(entries.get("syncedAt")))); }
    public boolean release(String e, Long id){ String type = redis.opsForHash().get(dataKey(e,id), "type"); if(type==null) return false; redis.opsForList().remove(inuseList(e,type), 1, String.valueOf(id)); redis.opsForSet().remove(inuseSet(e,type), String.valueOf(id)); redis.opsForList().leftPush(poolList(e,type), String.valueOf(id)); redis.opsForSet().add(poolSet(e,type), String.valueOf(id)); redis.delete(leaseKey(e,id)); return true; }
}
